### PR TITLE
fix unnecessary shift

### LINKED ISSUE #1365: OSMD: unnecessary x-shift
> * [ ]  Unnecessary x-shift from note alignment in test_note_alignment_long_distance
>   image

### PR DESCRIPTION
**Pull request by rvilarl**
fixes #1365
Only one visual difference:

**StaveNote Note_Heads_Placement___Simple Bravura**
**current**
StaveNote Note_Heads_Placement___Simple Bravura_current
**reference**
StaveNote Note_Heads_Placement___Simple Bravura_reference

### CODE REVIEW

File: src/stavenote.ts [hunk 1]
```diff
@@ -259,6 +259,12 @@ export class StaveNote extends StemmableNote {
               // shift lower voice right
               noteL.note.setXShift(xShift);
             }
+          } else if (noteU.note.hasStem()) {
+            noteU.stemDirection = -noteU.note.getStemDirection();
+            noteU.note.setStemDirection(noteU.stemDirection);
```
Comment (0xfe) [inline src/stavenote.ts:264]: Thanks Rodrigo. We should only change the stem direction in controlled situations. Can we move this into the `if (voices != 2)` branch? (otherwise we'll have weird issues with  stems changing direction in other situations.)

Comment (rvilarl) [reply src/stavenote.ts:264]: Hi Mohit, this is already, I believe, in a very controlled situation. All these conditions have to be fulfilled:
- there are two voices
- only one of the notes has stem (the other one is a whole)
- they are not in the same line
- they overlap (the stem overlaps with the whole)

There are no other visual differences in all the tests (this is the only one where the change of stem direction was applied)

Comment (0xfe) [reply src/stavenote.ts:264]: Thanks Rodrigo -- I didn't realize that this was inside the `voices === 2` branch.

**Comment by 0xfe** [comment]
Looks good, merging.
