### PR TITLE
point fixed on time signatures and clefs

### LINKED ISSUE #1527: Point 39/26: Time signatures and clefs
With 36 the time signatures are better adjusted to the target size. However the improvement is much more evident in the clefs, they are better positioned on the Y axis and the size is also better. I will look into this topic once this PR is merged. 
**Using 36 with no scale and no shiftY**
```js
 digits: {
    // used by TimeSignature objects
    shiftLine: -1,
    point: 36,
...
clef_default: {
      point: 36,
      gClef: {},
      fClef: {},
```
pptr-canvas_TimeSignature Time_Signature_multiple_staves_alignment_test Bravura_current
**Master**
```
digits: {
    // used by TimeSignature objects
    shiftLine: -1,
    point: 34,
...
clef_default: {
      point: 32,
      gClef: {
        scale: 1.1,
        shiftY: 1,
      },
      fClef: {
        shiftY: -0.5,
      },
```
pptr-canvas_TimeSignature Time_Signature_multiple_staves_alignment_test Bravura_reference

### PR DESCRIPTION
**Pull request by rvilarl**
fixes #1527 
Default 39
Small two-thirds (26)

As shown in #1527 the sizes are now better and the complexity of the common metrics is reduced.

### CODE REVIEW

**Comment by mscuthbert** [comment]
The new images look great to me.  I wonder if the TS should even be a little bit bigger because of the default gray staves?  But this looks to be an improvement.

**Comment by rvilarl** [comment]
> The new images look great to me. I wonder if the TS should even be a little bit bigger because of the default gray staves? But this looks to be an improvement.

Thanks! I want to leave the same point size to all elements in order to make sure that we keep the ratio decided by the creator of the font. The small clef is two thirds as specified by BB. I was testing with several sizes and I went for 36.

**Comment by rvilarl** [comment]
Master
pptr-Accidental Automatic_Accidentals Bravura svg_current
pptr-Accidental Automatic_Accidentals Leland svg_current
pptr-Accidental Automatic_Accidentals Petaluma svg_current
pptr-Annotation Bottom_Annotation Bravura svg_current
pptr-Annotation Bottom_Annotation Leland svg_current
pptr-Annotation Bottom_Annotation Petaluma svg_current

**Comment by rvilarl** [comment]
Reference(master)

pptr-Accidental Automatic_Accidentals Bravura svg_reference
pptr-Accidental Automatic_Accidentals Leland svg_reference
pptr-Accidental Automatic_Accidentals Petaluma svg_reference
pptr-Annotation Bottom_Annotation Bravura svg_reference
pptr-Annotation Bottom_Annotation Leland svg_reference
pptr-Annotation Bottom_Annotation Petaluma svg_reference

**Comment by rvilarl** [comment]
38

pptr-Accidental Automatic_Accidentals Bravura svg_current
pptr-Accidental Automatic_Accidentals Leland svg_current
pptr-Accidental Automatic_Accidentals Petaluma svg_current
pptr-Annotation Bottom_Annotation Bravura svg_current
pptr-Annotation Bottom_Annotation Leland svg_current
pptr-Annotation Bottom_Annotation Petaluma svg_current

**Comment by rvilarl** [comment]
@mscuthbert do you prefer 38 or even bigger?

**Comment by rvilarl** [comment]
40

pptr-Accidental Automatic_Accidentals Bravura svg_current
pptr-Accidental Automatic_Accidentals Leland svg_current
pptr-Accidental Automatic_Accidentals Petaluma svg_current
pptr-Annotation Bottom_Annotation Bravura svg_current
pptr-Annotation Bottom_Annotation Leland svg_current
pptr-Annotation Bottom_Annotation Petaluma svg_current

**Comment by rvilarl** [comment]
40 added for completion, thoughts?

**Comment by ronyeh** [comment]
How do the other top music engraving software handle this? Is this something that should be easily configurable by the developer (with a good default chosen by us)?

**Comment by rvilarl** [comment]
I was now looking at the noteheads point size because this should also be consistent with the size of the clefs and the size of the time signature.

This value is user configurable with a default. It is defined in Tables:
`static NOTATION_FONT_SCALE = 39;`

I would vote for 39 then and I would vote to change the code to read it from Tables.

**Comment by AaronDavidNewman** [comment]
The default note head size is 39.  But accidentals, ornaments and many note modifiers have a hard-coded default of 38.  These are in theory configurable but in practice, I think any change to this would break a lot of connection points.

For time signatures, though, I like the bigger look with 40, but I don't have strong opinions.  And these are easy for applications to customize.

I don't know about clefs.   Since they appear on every line they take more space overall.  I have no expertise on what is best and only a mild opinion that big time signatures, smaller clefs look best.

**Comment by rvilarl** [comment]
I have changed it to 39 (thanks @AaronDavidNewman) taken into account the default value (thanks @ronyeh) in tables if the metric is not defined.

**Comment by rvilarl** [comment]
@AaronDavidNewman I have also fixed the hardcoded 38, thank for the tip.

Ready to review.

**Comment by rvilarl** [comment]
39 (including fix of hardcoded 38s)
pptr-Accidental Accidental_Arrangement_Special_Cases Bravura svg_current
pptr-Accidental Accidental_Arrangement_Special_Cases Gonville svg_current
pptr-Accidental Accidental_Arrangement_Special_Cases Leland svg_current
pptr-Accidental Accidental_Arrangement_Special_Cases Petaluma svg_current
pptr-Accidental Accidental_Padding Bravura svg_current
pptr-Accidental Accidental_Padding Gonville svg_current
pptr-Accidental Accidental_Padding Leland svg_current
pptr-Accidental Accidental_Padding Petaluma svg_current

**Comment by rvilarl** [comment]
Is there any cocern with any of the changes included? I could revert some changes.

File: src/clef.ts [hunk 1]
```diff
@@ -143,7 +129,13 @@ export class Clef extends StaveModifier {
 
     this.setPosition(StaveModifierPosition.BEGIN);
     this.setType(type, size, annotation);
-    this.setWidth(Glyph.getWidth(this.clef.code, this.clef.point, `clef_${this.size}`));
+    this.setWidth(
+      Glyph.getWidth(
+        this.clef.code,
+        this.size == 'default' ? Tables.NOTATION_FONT_SCALE : (Tables.NOTATION_FONT_SCALE / 3) * 2,
```
Comment (ronyeh) [inline src/clef.ts:135]: Can you add a comment here to explain why it is multiplied by 2/3 ?

File: src/clef.ts [hunk 2]
```diff
@@ -200,9 +192,16 @@ export class Clef extends StaveModifier {
...
     this.applyStyle(ctx);
     ctx.openGroup('clef', this.getAttribute('id'));
-    Glyph.renderGlyph(ctx, this.x, stave.getYForLine(this.clef.line), this.clef.point, this.clef.code, {
-      category: `clef_${this.size}`,
-    });
+    Glyph.renderGlyph(
+      ctx,
+      this.x,
+      stave.getYForLine(this.clef.line),
+      this.size == 'default' ? Tables.NOTATION_FONT_SCALE : (Tables.NOTATION_FONT_SCALE / 3) * 2,
```
Comment (ronyeh) [inline src/clef.ts:199]: Same: Can you add a comment here to explain why it is multiplied by 2/3 ?

File: src/clefnote.ts [hunk 3]
```diff
@@ -60,9 +73,16 @@ export class ClefNote extends Note {
...
     const abs_x = this.getAbsoluteX();
 
-    Glyph.renderGlyph(ctx, abs_x, stave.getYForLine(this.clef.line), this.clef.point, this.clef.code, {
-      category: `clefNote_${this.size}`,
-    });
+    Glyph.renderGlyph(
+      ctx,
+      abs_x,
+      stave.getYForLine(this.clef.line),
+      this.size == 'default' ? Tables.NOTATION_FONT_SCALE : (Tables.NOTATION_FONT_SCALE / 3) * 2,
```
Comment (ronyeh) [inline src/clefnote.ts:80]: This same line of code appears a lot. And I'm not sure why it is multiplied by 2/3 in the non-default case.

Should we consolidate all of these `'default' ? Tables.NOTATION_FONT_SCALE : (Tables.NOTATION_FONT_SCALE / 3) * 2` into a helper method? If you don't think it's worth it, that's fine. Just curious.... because it shows up a lot.

**Review by ronyeh — APPROVED** [review]
Looks good, if you can add the comments where requested.
And investigate if you want to extract a helper method for the duplicated lines of code.

File: src/clef.ts (hunk 1 above)
Comment (rvilarl) [reply src/clef.ts:135]: Done in `Clef.getPoint`

File: src/clef.ts (hunk 2 above)
Comment (rvilarl) [reply src/clef.ts:199]: Done in `Clef.getPoint`

File: src/clefnote.ts (hunk 3 above)
Comment (rvilarl) [reply src/clefnote.ts:80]: Done in `Clef.getPoint`
