### PR TITLE
fix stem & flag heights

### LINKED ISSUE #941: Stems & Flags are possibly too high on Bravura & Petaluma
First off, I'm not an expert on how stems & flags should look. Someone with more expertise can chime in!

Here's what I noticed:

On the font sample that I typeset manually with the most recent versions of Bravura and Petaluma, I see that half, quarter, eighth and 16th notes are pretty much the same height.

https://vexflow-demo.vercel.app/images/font_sample.svg

This is mostly true with the Gonville sample that I rendered through LilyPond. Only the half note is a tiny bit shorter:

https://vexflow-demo.vercel.app/images/lilypond-gonville.svg

When a score is created with the most recent version of MuseScore, half, quarter, and eighth notes are the same height. 16th notes are a tiny bit taller, and then the stems grow noticeably higher on 32nd, 64th, and 128th notes.

bravura_vs_gonville_musescore

On my test page with VexFlow 3.0.9, it seems like Gonville is okay, but Bravura and Petaluma render very tall note stems.

gonville_bravura_petaluma_vexflow

In the samples generated by LilyPond, MuseScore, and manually in Affinity Designer, the innermost flag's tip is close to the note head. In the VexFlow 3.0.9 example, this is true for Gonville, but not for Bravura and Petaluma. In the latter two fonts, the 32nd, 64th, and 128th flags are far away from their note heads.

### PR DESCRIPTION
**Pull request by rvilarl**
Fixes #941

As expected many visual differences using Bravura and Petaluma. No visual differences using Gonville.

### CODE REVIEW

**Comment by rvilarl** [comment]
Auto_Beaming Maintain_Stem_Directions Bravura_Current
Auto_Beaming Maintain_Stem_Directions Bravura_Current
Auto_Beaming Maintain_Stem_Directions Bravura_Reference
Auto_Beaming Maintain_Stem_Directions Bravura_Reference
Note: The current approach affects also the notes with beams, leaving those closer to the notehad. I do not know if this wished.

**Comment by rvilarl** [comment]
Auto_Beaming Maintain_Stem_Directions Petaluma_Current
Auto_Beaming Maintain_Stem_Directions Petaluma_Current
Auto_Beaming Maintain_Stem_Directions Petaluma_ReferenceAuto_Beaming Maintain_Stem_Directions Petaluma_Reference

**Comment by rvilarl** [comment]
Grace_Notes Grace_Note_Stem_with_Beams Bravura_Current
Grace_Notes Grace_Note_Stem_with_Beams Bravura_Current
Grace_Notes Grace_Note_Stem_with_Beams Bravura_Reference
Grace_Notes Grace_Note_Stem_with_Beams Bravura_Reference

> Note: The current approach affects also the notes with beams, leaving those closer to the notehad. I do not know if this wished.

The beams are an issue for 128th duration notes.

**Comment by 0xfe** [comment]
Thanks for this change @rvilarl. I'm not sure that we're calculating stem heights correctly in all cases (I kinda just made up the rules). Either way, I think making them all consistent is a good first step, so this is good. Just not clear which way we should be consistent.

@mscuthbert do you have any references or examples for this? How should stems adjust as we add more beams?

**Comment by rvilarl** [comment]
@0xfe draft waiting for @mscuthbert feedback.

**Comment by mscuthbert** [comment]
Sorry -- end of the semester was rough.

Gould, Beyond Bars -- one and two beams do not affect stem length.  Each additional beam however needs to extend the stem height by .75 spaces, generally so that the closest beams in 16th and 32nd and 64th notes are the same distance from the notehead, but between 8th and 16th, the outer beams are the same distance.

Thus the Reference beams are better than the Current ones.

There are additional lengthening rules for notes on ledger lines (in treble clef, beam down, the highest beam can be no higher than the D line, so that the F line is clearly visible) and for 64th notes (beams need to be slightly farther apart than for 16th and 32nd notes.  128th notes are always a beaming problem.)  But those are tiny tweaks after the big ones are in.

For the unbeamed notes, however, Current is better than Reference.  For the flags (tails in British terminology) 8th and 16th notes have the same stem length.  32nd and shorter notes have extended stem lengths, but the two flags closest to the notehead need to be aligned with those of a 16th note.  The Bravura Reference 32nd note looks especially displeasing to me.

**Comment by mscuthbert** [comment]
(as an aside, we definitely need this same reference test done with notes on close ledger lines (A, and C above treble clef, and C and A below) and also on distant ledger lines and spaces (high A 4.5 ledgers above treble and low D 4 ledgers below would work well), to make sure that the flags and beams not crossing ledger lines.  Or if they are, at least letting us know that they are as something to fix later.

**Comment by rvilarl** [comment]
@mscuthbert thanks for the feedback. 
Here the actual ouput:
**Auto_Beaming Maintain_Stem_Directions Bravura**
**current**
Auto_Beaming Maintain_Stem_Directions Bravura_Current
**reference**
Auto_Beaming Maintain_Stem_Directions Bravura_Reference

**Grace_Notes Grace_Note_Stem_with_Beams**
**current**
Grace_Notes Grace_Note_Stem_with_Beams_1 Bravura
**reference**
Grace_Notes Grace_Note_Stem_with_Beams Bravura

**Comment by rvilarl** [comment]
> (as an aside, we definitely need this same reference test done with notes on close ledger lines (A, and C above treble clef, and C and A below) and also on distant ledger lines and spaces (high A 4.5 ledgers above treble and low D 4 ledgers below would work well), to make sure that the flags and beams not crossing ledger lines. Or if they are, at least letting us know that they are as something to fix later.

And the addtional tests (@mscuthbert hopefully I understood correctly)
Grace_Notes Grace_Note_Stem_with_Beams_2 Bravura
Grace_Notes Grace_Note_Stem_with_Beams_3 Bravura

**Comment by rvilarl** [comment]
I adapted a percussion test because somehow the reference output did not pass to the spec. The current output does passed now to the spec and the reference (no visual difference).

Percussion Percussion_Basic0 Bravura

**Comment by rvilarl** [comment]
@0xfe ready to review.

**Comment by mscuthbert** [comment]
> > (as an aside, we definitely need this same reference test done with notes on close ledger lines (A, and C above treble clef, and C and A below) and also on distant ledger lines and spaces (high A 4.5 ledgers above treble and low D 4 ledgers below would work well), to make sure that the flags and beams not crossing ledger lines. Or if they are, at least letting us know that they are as something to fix later.
> 
> And the addtional tests (@mscuthbert hopefully I understood correctly)

Those look good; but could you also do distant/lots of ledger line tests (A6 and C3 in treble clef).  Those are the ones that I'm particularly concerned with the staff lines not being visible?

**Comment by mscuthbert** [comment]
btw -- the normal concerns about beams and lines intersecting or not are much less on Vexflow than printed music thanks to Mohit's initial genius decision to use gray staff lines.

File: tests/stavenote_tests.ts [hunk 1]
```diff
@@ -279,12 +279,12 @@ function stemExtensionPitch(): void {
...
-      whole_note.getStemExtension(),
-      -1 * Flow.STEM_HEIGHT,
-      'For ' + keys.toString() + ' whole_note StemExtension must always be -1 * Flow.STEM_HEIGHT'
-    );
+    //    const whole_note = new StaveNote({ keys: keys, duration: 'w' });
+    //    equal(
+    //      whole_note.getStemExtension(),
+    //      -1 * Flow.STEM_HEIGHT,
+    //      'For ' + keys.toString() + ' whole_note StemExtension must always be -1 * Flow.STEM_HEIGHT'
+    //    );
```
Comment (0xfe) [inline tests/stavenote_tests.ts:287]: Not clear why this is commented?

File: tests/percussion_tests.ts [hunk 2]
```diff
@@ -134,7 +134,7 @@ const basic0 = createSingleMeasureTest((f) => {
 
   f.Beam({ notes: voice0.getTickables() as StemmableNote[] });
   f.Beam({ notes: voice1.getTickables().slice(0, 2) as StemmableNote[] });
-  f.Beam({ notes: voice1.getTickables().slice(3, 6) as StemmableNote[] });
+  f.Beam({ notes: voice1.getTickables().slice(3, 5) as StemmableNote[] });
```
Comment (0xfe) [inline tests/percussion_tests.ts:137]: Not clear about this change either.

File: src/fonts/gonville_metrics.ts [hunk 3]
```diff
@@ -179,12 +179,26 @@ export const GonvilleMetrics = {
...
       },
       flag64thDown: {
         shiftX: -0.16,
+        shiftY: 13,
       },
       flag128thDown: {
         shiftX: -0.16,
+        shiftY: 22,
+      },
+      flag8thUp: {},
```
Comment (0xfe) [inline src/fonts/gonville_metrics.ts:192]: I think you don't need these empty ones, because you can set a default in the lookup.

File: src/stavenote.ts [hunk 4]
```diff
@@ -1157,9 +1161,9 @@ export class StaveNote extends StemmableNote {
       const flagY =
         this.getStemDirection() === Stem.DOWN
           ? // Down stems are below the note head and have flags on the right.
-            y_top - noteStemHeight + 2
+            y_top - noteStemHeight + 2 - (this.flag !== undefined ? this.flag.checkMetrics().y_shift : 0)
```
Comment (0xfe) [inline src/stavenote.ts:1164]: Can we separate this edit into two pieces?

```typescript
const extension = this.hasFlag() ? this.flag.checkMetrics().y_shift : 0;

this.flagY = ... 
  y_top - noteStemHeight + extension + 2
...
```

**Review by 0xfe — COMMENTED** [review]
Thanks Rodrigo -- it does look a lot better. Some comments (not clear to me the impact of the removed stem_extension on the rest of the tests.) What do the visual diffs look like?

File: tests/stavenote_tests.ts (hunk 1 above)
Comment (rvilarl) [reply tests/stavenote_tests.ts:287]: This is no longer true look at note.getStemExtension()

File: tests/percussion_tests.ts (hunk 2 above)
Comment (rvilarl) [reply tests/percussion_tests.ts:137]: In order to get the same result like in master. For some reason master was beaming only two notes

File: src/stavenote.ts (hunk 4 above)
Comment (rvilarl) [reply src/stavenote.ts:1164]: done

File: src/fonts/gonville_metrics.ts (hunk 3 above)
Comment (rvilarl) [reply src/fonts/gonville_metrics.ts:192]: Done

**Comment by rvilarl** [comment]
@0xfe There are 79 differences. I would say all as expected.

**Comment by rvilarl** [comment]
Accidental Accidental_Padding Bravura
Accidental Accidental_Padding Bravura_Current
Accidental Accidental_Padding Bravura_Reference
Accidental Accidental_Padding Gonville
Accidental Accidental_Padding Gonville_Current
Accidental Accidental_Padding Gonville_Reference
Accidental Accidental_Padding Petaluma
Accidental Accidental_Padding Petaluma_Current
Accidental Accidental_Padding Petaluma_Reference

**Comment by rvilarl** [comment]
Auto_Beaming Duration_Based_Secondary_Beam_Breaks Bravura
Auto_Beaming Duration_Based_Secondary_Beam_Breaks Bravura_Current
Auto_Beaming Duration_Based_Secondary_Beam_Breaks Bravura_Reference
Auto_Beaming Duration_Based_Secondary_Beam_Breaks Gonville
Auto_Beaming Duration_Based_Secondary_Beam_Breaks Gonville_Current
Auto_Beaming Duration_Based_Secondary_Beam_Breaks Gonville_Reference
Auto_Beaming Duration_Based_Secondary_Beam_Breaks Petaluma
Auto_Beaming Duration_Based_Secondary_Beam_Breaks Petaluma_Current
Auto_Beaming Duration_Based_Secondary_Beam_Breaks Petaluma_Reference
Auto_Beaming Duration_Based_Secondary_Beam_Breaks_2 Bravura
Auto_Beaming Duration_Based_Secondary_Beam_Breaks_2 Bravura_Current
Auto_Beaming Duration_Based_Secondary_Beam_Breaks_2 Bravura_Reference
Auto_Beaming Duration_Based_Secondary_Beam_Breaks_2 Gonville
Auto_Beaming Duration_Based_Secondary_Beam_Breaks_2 Gonville_Current
Auto_Beaming Duration_Based_Secondary_Beam_Breaks_2 Gonville_Reference
Auto_Beaming Duration_Based_Secondary_Beam_Breaks_2 Petaluma
Auto_Beaming Duration_Based_Secondary_Beam_Breaks_2 Petaluma_Current
Auto_Beaming Duration_Based_Secondary_Beam_Breaks_2 Petaluma_Reference
Auto_Beaming Flat_Beams_Down Bravura
Auto_Beaming Flat_Beams_Down Bravura_Current
Auto_Beaming Flat_Beams_Down Bravura_Reference
Auto_Beaming Flat_Beams_Down Gonville
Auto_Beaming Flat_Beams_Down Gonville_Current
Auto_Beaming Flat_Beams_Down Gonville_Reference
Auto_Beaming Flat_Beams_Down Petaluma
Auto_Beaming Flat_Beams_Down Petaluma_Current
Auto_Beaming Flat_Beams_Down Petaluma_Reference
Auto_Beaming Flat_Beams_Mixed_Direction Bravura
Auto_Beaming Flat_Beams_Mixed_Direction Bravura_Current
Auto_Beaming Flat_Beams_Mixed_Direction Bravura_Reference
Auto_Beaming Flat_Beams_Mixed_Direction Gonville
Auto_Beaming Flat_Beams_Mixed_Direction Gonville_Current
Auto_Beaming Flat_Beams_Mixed_Direction Gonville_Reference
Auto_Beaming Flat_Beams_Mixed_Direction Petaluma
Auto_Beaming Flat_Beams_Mixed_Direction Petaluma_Current
Auto_Beaming Flat_Beams_Mixed_Direction Petaluma_Reference
Auto_Beaming Maintain_Stem_Directions Bravura
Auto_Beaming Maintain_Stem_Directions Bravura_Current
Auto_Beaming Maintain_Stem_Directions Bravura_Reference
Auto_Beaming Maintain_Stem_Directions Gonville
Auto_Beaming Maintain_Stem_Directions Gonville_Current
Auto_Beaming Maintain_Stem_Directions Gonville_Reference
Auto_Beaming Maintain_Stem_Directions Petaluma
Auto_Beaming Maintain_Stem_Directions Petaluma_Current
Auto_Beaming Maintain_Stem_Directions Petaluma_Reference
Auto_Beaming Maintain_Stem_Directions___Beam_Over_Rests Bravura
Auto_Beaming Maintain_Stem_Directions___Beam_Over_Rests Bravura_Current
Auto_Beaming Maintain_Stem_Directions___Beam_Over_Rests Bravura_Reference
Auto_Beaming Maintain_Stem_Directions___Beam_Over_Rests Gonville
Auto_Beaming Maintain_Stem_Directions___Beam_Over_Rests Gonville_Current
Auto_Beaming Maintain_Stem_Directions___Beam_Over_Rests Gonville_Reference
Auto_Beaming Maintain_Stem_Directions___Beam_Over_Rests Petaluma
Auto_Beaming Maintain_Stem_Directions___Beam_Over_Rests Petaluma_Current
Auto_Beaming Maintain_Stem_Directions___Beam_Over_Rests Petaluma_Reference
Auto_Beaming Simple_Auto_Beaming Bravura
Auto_Beaming Simple_Auto_Beaming Bravura_Current
Auto_Beaming Simple_Auto_Beaming Bravura_Reference
Auto_Beaming Simple_Auto_Beaming Gonville
Auto_Beaming Simple_Auto_Beaming Gonville_Current
Auto_Beaming Simple_Auto_Beaming Gonville_Reference
Auto_Beaming Simple_Auto_Beaming Petaluma
Auto_Beaming Simple_Auto_Beaming Petaluma_Current
Auto_Beaming Simple_Auto_Beaming Petaluma_Reference

**Comment by rvilarl** [comment]
Beam Complex_Beams_with_Annotations Bravura
Beam Complex_Beams_with_Annotations Bravura_Current
Beam Complex_Beams_with_Annotations Bravura_Reference
Beam Complex_Beams_with_Annotations Gonville
Beam Complex_Beams_with_Annotations Gonville_Current
Beam Complex_Beams_with_Annotations Gonville_Reference
Beam Complex_Beams_with_Annotations Petaluma
Beam Complex_Beams_with_Annotations Petaluma_Current
Beam Complex_Beams_with_Annotations Petaluma_Reference
Beam Complex_Beams_with_Articulations Bravura
Beam Complex_Beams_with_Articulations Bravura_Current
Beam Complex_Beams_with_Articulations Bravura_Reference
Beam Complex_Beams_with_Articulations Gonville
Beam Complex_Beams_with_Articulations Gonville_Current
Beam Complex_Beams_with_Articulations Gonville_Reference
Beam Complex_Beams_with_Articulations Petaluma
Beam Complex_Beams_with_Articulations Petaluma_Current
Beam Complex_Beams_with_Articulations Petaluma_Reference
Beam Partial_Beam Bravura
Beam Partial_Beam Bravura_Current
Beam Partial_Beam Bravura_Reference
Beam Partial_Beam Gonville
Beam Partial_Beam Gonville_Current
Beam Partial_Beam Gonville_Reference
Beam Partial_Beam Petaluma
Beam Partial_Beam Petaluma_Current
Beam Partial_Beam Petaluma_Reference

**Comment by rvilarl** [comment]
[rest.zip](https://github.com/0xfe/vexflow/files/7738736/rest.zip)

File: tests/percussion_tests.ts (hunk 2 above)
Comment (0xfe) [reply tests/percussion_tests.ts:137]: Gotcha, thanks!

File: src/stemmablenote.ts [hunk 5]
```diff
@@ -184,11 +184,14 @@ export abstract class StemmableNote extends Note {
...
-      return this.getStemDirection() === Stem.UP ? glyph.stem_up_extension : glyph.stem_down_extension;
+    // Use stem_beam_extension with beams
+    if (this.beam) {
+      return glyph.stem_beam_extension;
     }
 
-    return 0;
+    const flagCode =
+      this.getStemDirection() === Stem.DOWN ? this.glyph.code_flag_downstem : this.glyph.code_flag_upstem;
+    return Math.abs(Tables.MUSIC_FONT_STACK[0].lookupMetric(`glyphs.flag.${flagCode}.shiftY`, 0));
```
Comment (0xfe) [inline src/stemmablenote.ts:194]: Can we use `Tables.currentMusicFont` here instead of `MUSIC_FONT_STACK[0]`?

**Review by 0xfe — COMMENTED** [review]
Last one :-)

File: src/stemmablenote.ts (hunk 5 above)
Comment (rvilarl) [reply src/stemmablenote.ts]: Done :)

**Comment by rvilarl** [comment]
Ready to merge.

**Comment by 0xfe** [comment]
Thanks!
