### PR TITLE
Issue 1301: Fix vertical placement of Bend and Vibrato in tab staves

### LINKED ISSUE #1301: Fix bend/vibrato vertical placement
Bend and annotation now update the modifier context with its height.  One side-effect of this is that the vibrato now appears above the bend, and the 'tap' appears above the bend instead of at the same level.

In the case of vibrato, it already checks for a bend and moves itself down if it detects one.  It just needs to add another line, since the bend is increasing the line height.

For annotation and bend, it doesn't really make sense to do that because an annotation could be anything, there is no way to tell it is the 'Tap' for a bend.  So we can add a specific tap for a bend.  

Is a 'Tap' always the letter 'T'?  Not a guitar person.,..

Should be:

image

image

Is currently:
image
image

### PR DESCRIPTION
**Pull request by AaronDavidNewman**
Fix #1301.

Vibrato places itself below Bend if there's a bend.  Bend has optional 'tap' parameter that puts the tap to the left of the bend, instead of using an Annotation:

image

image

Visual regression showed only the expected changes.

### CODE REVIEW

File: src/bend.ts [hunk 1]
```diff
@@ -5,7 +5,7 @@ import { Element } from './element';
 import { FontInfo } from './font';
 import { Modifier } from './modifier';
 import { ModifierContextState } from './modifiercontext';
-import { Stave } from './stave';
+import { TextFormatter } from './textformatter';
 import { Tables } from './tables';
```
Comment (rvilarl) [inline src/bend.ts:9]: Tables is no longer required, delete the line.

File: tests/vibrato_tests.ts [hunk 2]
```diff
@@ -11,6 +11,7 @@ const VibratoTests = {
   Start(): void {
     QUnit.module('Vibrato');
     const run = VexFlowTests.runTests;
+    run('Vibrato with Bend', withBend);
```
Comment (rvilarl) [inline tests/vibrato_tests.ts:14]: This test seems to be called twice. Delete one instance.

File: tests/vibrato_tests.ts [hunk 3]
```diff
@@ -103,8 +104,8 @@ function withBend(options: TestOptions, contextBuilder: ContextBuilder): void {
       positions: [{ str: 2, fret: 10 }],
       duration: 'q',
     })
-      .addModifier(0, new Bend('Full', false))
-      .addModifier(0, new Vibrato().setVibratoWidth(60)),
+      .addModifier(0, new Vibrato().setVibratoWidth(60))
+      .addModifier(0, new Bend('Full', false)),
```
Comment (rvilarl) [inline tests/vibrato_tests.ts:108]: Does the call order have any effect? If not it seems that vibrato_tests.ts has no change and should stay as it was.

**Review by rvilarl — APPROVED** [review]

File: tests/vibrato_tests.ts (hunk 3 above)
Comment (AaronDavidNewman) [reply tests/vibrato_tests.ts]: Changed it back.   Order doesn't matter.

File: tests/vibrato_tests.ts (hunk 2 above)
Comment (AaronDavidNewman) [reply tests/vibrato_tests.ts]: oops...ok

**Comment by AaronDavidNewman** [comment]
ready for merge

**Comment by 0xfe** [comment]
LGTM. Thanks for this. We should add this to the changelog.
